jamovi/jamovi

client/analysisui/formatdef.js, client/analysisui/gridvariablestargetlist.js, client/analysisui/option.js, client/analysisui/optionsview.js
- Fixed issues with ANOVA
- Added support for single variables
=> Fixed variable support issues.

client/analysisui/gridvariablestargetlist.js, client/analysisui/layoutcell.js, client/analysisui/layoutgrid.js, client/analysisui/layoutvariablesview.js, client/analysisui/main.less
- Also optimised some layout code
=> Added Icons to variables

client/analysisui/gridvariablestargetlist.js, client/analysisui/layoutgrid.js, client/analysisui/layoutvariablesview.js, client/analysisui/main.js, client/analysisui/main.less, client/analysisui/optionsview.js, client/analysisui/selectablelayoutgrid.js
- Added TTest UI's
- Layout fixes
=> Updates to Analyses UI

client/analysisui/formatdef.js, client/analysisui/gridcheckbox.js, client/analysisui/gridcombobox.js, client/analysisui/gridradiobutton.js, client/analysisui/gridtextbox.js, client/analysisui/gridvariablestargetlist.js, client/analysisui/layoutaction.js, client/analysisui/layoutactionmanager.js, client/analysisui/layoutactionresource.js, client/analysisui/layoutdef.js, client/analysisui/layoutgrid.js, client/analysisui/layoutvariablesview.js, client/analysisui/main.js, client/analysisui/main.less, client/analysisui/optioncontrol.js, client/analysisui/optioncontrolbase.js, client/analysisui/optionlistcontrol.js, client/analysisui/optionsview.js, client/analysisui/propertySupplier.js, client/analysisui/selectablelayoutgrid.js, client/main/silky.css
- Added actions to allow for custom UI modifications in the UI
definitions file.
- Fixed some layout bugs
=> UI Definitions

client/analysisui/controlbase.js, client/analysisui/controlcontainer.js, client/analysisui/controlmanager.js, client/analysisui/gridcheckbox.js, client/analysisui/gridcombobox.js, client/analysisui/gridcontrol.js, client/analysisui/gridoptionlistcontrol.js, client/analysisui/gridradiobutton.js, client/analysisui/gridtextbox.js, client/analysisui/gridvariablestargetlist.js, client/analysisui/layoutactionmanager.js, client/analysisui/layoutcell.js, client/analysisui/layoutgroupview.js, client/analysisui/layoutvariablesview.js, client/analysisui/main.js, client/analysisui/main.less, client/analysisui/optioncontrolbase.js, client/analysisui/optionlistcontrol.js, client/analysisui/optionsview.js, client/analysisui/silkycontrolmanager.js, client/main/main.js, client/main/optionspanel.js
- fixed issue with table loosing mouse function.
- improved option control support
- added stage property for ui controls
- other improvements
=> Various fixes and updates

client/analysisui/controlbase.js, client/analysisui/controlcontainer.js, client/analysisui/gridcheckbox.js, client/analysisui/gridcombobox.js, client/analysisui/gridoptioncontrol.js, client/analysisui/gridoptionlistcontrol.js, client/analysisui/gridradiobutton.js, client/analysisui/gridtextbox.js, client/analysisui/gridvariablestargetlist.js, client/analysisui/layoutdef.js, client/analysisui/layoutgrid.js, client/analysisui/layoutgroupview.js, client/analysisui/layoutvariablesview.js, client/analysisui/main.less, client/analysisui/optioncontrol.js, client/analysisui/optioncontrolbase.js, client/analysisui/optionlistcontrol.js, client/analysisui/optionsview.js, client/analysisui/silkycontrolmanager.js, client/main/main.js, client/main/splitpanelsection.js
- fixed scrollbar issue when loading first analyses
- improved UI background workings
=> UI Updates and fixes

client/analysisui/controlmanager.js, client/analysisui/gridcombobox.js, client/analysisui/gridvariablestargetlist.js, client/analysisui/layoutcell.js, client/analysisui/layoutgrid.js, client/analysisui/layoutvariablesview.js, client/analysisui/listitemcombobox.js, client/analysisui/listitemcontrol.js, client/analysisui/listitemlabel.js, client/analysisui/listitemvariablelabel.js, client/analysisui/main.js, client/analysisui/option.js, client/analysisui/optionlistcontrol.js, client/analysisui/optionsview.js, client/analysisui/propertySupplier.js, client/analysisui/silkycontrolmanager.js
- closes #37
- closes #38
- Adds contrast support
- fixes some layout issues
=> Various Fixes and additions

client/analysisui/formatdef.js, client/analysisui/gridvariablestargetlist.js, client/analysisui/layoutgrid.js, client/analysisui/layoutgroupview.js, client/analysisui/layoutvariablesview.js, client/analysisui/targetlistvaluefilter.js
- added the interactions when multi selecting from the model creator
=> Fixes to list filters and list interactions

client/analysisui/gridvariablestargetlist.js, client/analysisui/layoutcell.js, client/analysisui/selectablelayoutgrid.js
- closes #36
- added command support for list selection
=> fixes selection reversal issue

client/resultsview/table.js
There is a problem with the table not showing up in it's entirety when swapRowsColumns is true.
Only Maximum value is showing for some reason.
=> switching descriptives orientation in table view

client/main/backstage.css, client/main/backstage.js, server/instance.py
- also fixed the python save function to handle virtual paths
=> Added Save As Support

client/main/backstage.css, client/main/backstage.js
- spacings
- enter on save as filename
=> Fixed various issues with backstage

client/main/backstage.css, client/main/backstage.js
- added under development to OSF
- fixed browse button behaviour
=> Various backstage improvements

client/analysisui/gridcheckbox.css, client/analysisui/gridcombobox.js, client/analysisui/gridradiobutton.css, client/analysisui/gridtextbox.css, client/analysisui/layoutcell.js, client/analysisui/layoutcollapseview.css, client/analysisui/layoutcollapseview.js, client/analysisui/layoutgroupview.css, client/analysisui/layoutgroupview.js, client/analysisui/layoutvariablesview.css, client/analysisui/layoutvariablesview.js, client/analysisui/main.js, client/analysisui/main.less, client/analysisui/rmanovafactorscontrol.css, client/analysisui/silkycontrolmanager.js, client/main/backstage.js
- must have the latest silkyR as well
=> Modifications to layout manager

client/analysisui/dragndrop.js, client/analysisui/gridvariablestargetlist.js
=> fixed double value changed event

client/analysisui/gridtargetlist.js, client/analysisui/layoutcell.js, client/analysisui/layoutgridbordersupport.js, client/analysisui/main.less, client/analysisui/optionlistcontrol.js
- fixed issue with cell location classing
- added divider to target lists if there is more then one column
=> Various fixes

client/analysisui/enumarraypropertyfilter.js, client/analysisui/gridtargetlist.js, client/analysisui/gridvariablestargetlist.js, client/analysisui/layoutvariablesview.css, client/analysisui/main.less
NOTE: does not stop you from adding an incorrect variable yet.
=> Added filter icons to variable lists

client/analysisui/gridtargetlist.js, client/analysisui/gridvariablestargetlist.js, client/analysisui/layoutvariablesview.js
NOTE: variable suppliers don't yet filter
=> Added variable target list filtering

client/analysisui/gridvariablestargetlist.js, client/analysisui/rmanovafactorscontrol.js
- also made permitted types include suggested types
=> Fixed selection issue in RM Anova

client/main/backstage.js
- file system item ids were changed to different values
=> Fixed issue with file browser

client/analysisui/main.js, client/analysisui/optionsview.js
=> Fixed issue with repeated model terms

client/main/backstage.js
- code improvements
- saveAs inserts the filename if it exists
- fixed issue where files would look like folders after a save.
=> Fixed up open/save functions

client/main/dataset.js
=> Fixed issue with data editting

client/analysisui/gridvariablestargetlist.js, client/main/options.js
- fixed issue with suggested icons sinking below variables list.
- fixed issue when option is missing default value.
=> Fixed some various issues

client/analysisui/gridvariablestargetlist.js, client/analysisui/layoutgrid.js, client/main/tableview.css, client/main/tableview.js
- added selected cell always in view
- made selected cell row and column headers the same colour
- moved some code around.
=> Few updates to table view

client/analysisui/actions.js, client/analysisui/dragndrop.js, client/analysisui/format.js, client/analysisui/formatdef.js, client/analysisui/gridtargetlist.css, client/analysisui/gridtargetlist.js, client/analysisui/layoutaction.js, client/analysisui/layoutactionmanager.js, client/analysisui/layoutgrid.js, client/analysisui/layoutsupplierview.js, client/analysisui/listitemcombobox.js, client/analysisui/listitemcontrol.js, client/analysisui/listitemlabel.js, client/analysisui/listitemvariablelabel.js, client/analysisui/main.js, client/analysisui/main.less, client/analysisui/optioncontrolbase.js, client/analysisui/optionlistcontrol.js, client/analysisui/propertysupplier.js, client/analysisui/silkycontrolmanager.js
- added new control to RM Anova
- added reordering of lists
- upgraded ui definitions
=> various updates

client/analysisui/main.less, client/main/backstage.css, client/main/backstage.js, client/main/optionspanel.js, server/resources/client/assets/jamovi-document.svg
- attempted fix for more than one analyses with same name.
- fixed save as with empty name. closes #136
- fixed issue of retaining inappropriate extension. closes #133
- fixed issue with adding multiple variables to list. closes #129
- added new icon for omv files. closes #97
=> Fixed various issues

client/analysisui/actions.js
=> Update to UI Base object

client/analysisui/gridcheckbox.js
- checkboxes can now link to arrays of strings
=> Added support for NMXLists

client/analysisui/actions.js
=> Fixed analysis options issue

client/analysisui/listitemcontrol.js, client/analysisui/listitemvariablelabel.js
=> Fixed rendering issue

client/analysisui/option.js, client/analysisui/options.js, client/main/analyses.js, client/main/options.js
=> Fixed default value issue with options

client/main/backstage.js, client/main/instance.js, server/jamovi/server/instance.py, server/jamovi/server/jamovi.proto
=> Added check for existing file when saving

client/analysisui/layoutgroupview.js, client/main/analyses.js, client/main/options.js
- options where no populating correctly.
=> Fixed issue with loading files

client/main/backstage.js, client/main/instance.js
- added method for jonathon in instance
=> Added menu for CSV Export

client/main/backstage.js, client/main/instance.js
=> Fixed issues with export ui

client/analysisui/gridtargetcontrol.js, client/analysisui/optionlistcontrol.js
=> Fixed variable lists not always updating for new columns

client/analysisui/gridtextbox.js, client/analysisui/option.js
- fixed textbox to stretch when told.
- made option more robust.
=> small fixes

client/analysisui/dragndrop.js, client/analysisui/gridcontrol.js, client/analysisui/gridtextbox.js
- drag and drop issues
- textbox sizing issue
=> Fixed Issues

client/analysisui/dragndrop.js, client/analysisui/gridtargetcontrol.js
- allows for the specifying of drop area
- allows for overflow of dropped items
=> Improvements to drop behaviour for embedded list

client/analysisui/dragndrop.js, client/analysisui/gridtargetcontrol.js
- selecting multiple and clicking the add button now adds multiple to
the cells control.
=> Fix for RM Anova cells add button behaviour

client/analysisui/main.less
- electron 0.6.7 has fixed windows rendering issues.
=> Fix option page font sizes

client/main/utils/formatio.js
- Tables no longer split across pages.
=> Imporved PDF export

client/main/backstage.css, client/main/backstage.js, client/main/results.js, server/jamovi/server/formatio/__init__.py
- added spinner to export and save
- fixed icons on recents
=> Some fixes

client/analysisui/dragndrop.js, client/analysisui/gridtextbox.js, client/analysisui/layoutaction.js, client/analysisui/layoutactionmanager.js, client/analysisui/optionlistcontrol.js, client/analysisui/optionsview.js
- required for the cfa analysis to function properly
=> Update to ui event system

client/main/ribbon/ribbonbutton.css, client/main/ribbon/ribbonmenu.css
- solved issue with scroll bar
- closes #266
=> Brought analyse button layout inline with new button system

client/main/main.js, client/main/ribbon.js
- returns to last tab
- File tab doesn't effect toolbar
=> Improved tab behaviour

client/analysisui/actions.js, client/analysisui/formatdef.js, client/analysisui/gridtextbox.css, client/analysisui/layoutvariablesview.js, client/analysisui/main.less, client/analysisui/termlabel.js, client/analysisui/variablelabel.js, client/main/analyses.js, client/main/instance.js, client/main/options.js, client/main/optionspanel.js
- also fixed issue with VariableLists
- fixed issues with CFA
=> Added insert, apend, delete column support for option panel

client/analysisui/gridcheckbox.css, client/analysisui/gridcheckbox.js, client/analysisui/gridtextbox.css, client/analysisui/gridtextbox.js, client/analysisui/main.less, client/analysisui/optionlistcontrol.css, client/analysisui/optionlistcontrol.js
- added suggested values support to textboxes
- fixed issues with multi column list support
- fixed issue with list column headers
=> Improvements and fixes

client/main/backstage.js
=> Fixed issue with backstage

client/analysisui/actions.js, client/analysisui/formatdef.js, client/analysisui/gridtextbox.css, client/analysisui/gridtextbox.js
- improves ui list support
- closes #293
=> fixes various issues

client/main/vareditor/computedvarwidget.css, client/main/vareditor/computedvarwidget.js
Also changed textarea to contenteditable div
=> Formula's: tweaked error box

client/main/main.less, client/main/vareditor/computedvarwidget.css, client/main/vareditor/computedvarwidget.js, client/main/vareditor/datavarwidget.css, client/main/vareditor/datavarwidget.js, client/main/vareditor/editorwidget.js, client/main/vareditor/newvarwidget.css, client/main/vareditor/newvarwidget.js, client/main/vareditor/variablemodel.js, client/main/variableeditor.css, server/jamovi/server/compute/functions.py, server/jamovi/server/compute/transmogrifier.py
=> Formulas: added "new variable" buttons

client/main/vareditor/computedvarwidget.js, client/main/variableeditor.css
added backticks for variable names with
Fixed squashing variable view issue
=> Formulas: small tweaks

client/main/vareditor/variablemodel.js
=> improves variable editor behaviour

client/analysisui/gridtextbox.js, client/analysisui/termlabel.js
=> Fixed issue with TermLabel 'format' property

client/analysisui/layoutgroupview.js
=> Fixed block header formatting

client/main/contextmenu.css, client/main/contextmenu.js, client/main/contextmenu/contextmenubutton.css, client/main/contextmenu/contextmenubutton.js, client/main/ribbon/ribbongroup.js
=> Added window edge handling to context menus

client/main/vareditor/computedvarwidget.js, client/main/vareditor/datavarwidget.js, client/main/vareditor/editorwidget.js, client/main/vareditor/newvarwidget.js, client/main/vareditor/recodedvarwidget.js, client/main/vareditor/variablemodel.js
- closes #360
- also added check to column widget refresh for the event that the
widget has changed column in the mean time.
=> Fixed issue with levels being removed from column

engine/engine/engine.cpp, engine/engine/host.cpp, engine/engine/host.h
- terminates engine if unexpectedly orphaned
=> added engine termination method

client/main/tableview.css, client/main/tableview.js
- End edit with arrow key
- added selected all
- closes 356
=> Improved spreadsheet selection

client/main/backstage.js
- made browse modal
- added suggested file name
- remember save/open locations
- fixed issue with special path recognition
=> Fixed up issues with backstage

client/analysisui/layoutcollapseview.css
- added mouse hover discoverability
- added transition to the collapse arrow
=> Improved the collapse button

client/analysisui/controlcontainer.js
- fixed issues caused by fixed cells.
=> Fixed issue with layout manager

client/main/tableview.js
=> Fixed issue with dbl clicking the table select all

client/main/jamovi.css, client/main/ribbon.css
- centered the dots for windows
- fixed hover issue because of windows bottons
- closes #410
=> Fixed up issues with tools button

client/analysisui.html, client/analysisui/main.js, client/analysisui/main.less, client/main/ribbon/appmenu.js, client/main/ribbon/ribbonbutton.js, client/main/store.css, client/main/store.js, client/main/vareditor/editorwidget.js, client/main/vareditor/variablemodel.js, client/main/variableeditor.css, client/main/variableeditor.js, client/package.json
- closes #140
- closes #326
- added tooltips to symbol buttons
=> variable editor improvements and tooltips

client/main/dataset.js, client/main/vareditor/filterwidget.js
- also fixed issue with selection moving when formula editor clicked.
=> set filter visibility to true by default

client/main/vareditor/computedvarwidget.css
=> Changes for the computed var formula text box

client/main/vareditor/computedvarwidget.js, client/main/vareditor/editorwidget.js, client/main/vareditor/variablemodel.js
=> Fixed issue with column names/desc

client/main/tableview.js
- added ability to select multiple rows / columns with the mouse from
the headers
- right click menu works with multiple rows / columns selected
- closes #351
=> improved table selection handling

client/main/ribbon/appmenu.js
=> color palette: added default ggplot2 theme as "hadley"

client/main/tableview.js, server/jamovi/server/formatio/omv.py, server/jamovi/server/instance.py, server/jamovi/server/instancemodel.py
- fixed saving issue with transform suffix
- fixed issue with appending new columns when filters were hidden
- fixed issue with inserting columns
=> Fixed some issues from testing

client/main/vareditor/datavarwidget.js, client/main/vareditor/variablemodel.js
- fixed reordering issue
- fixed issue with level selection and movement to multiple selection
=> Fix for the data variable levels issue

client/main/dataset.js, server/jamovi/server/instance.py
=> Fixed issue with pasting something larger than the avaliable space

client/analysisui/layoutcell.js, client/analysisui/layoutgrid.js
- changed to a system of progressively adding items to the layout
manager to minimise lag created by datasets with many columns.
=> made mods to improve efficiency for many data columns

client/assets/modules-analyses-arrow.svg, client/main/instance.js, client/main/modules.js, client/main/ribbon.js, client/main/ribbon/analysetab.js, client/main/ribbon/ribbonmenu.css, client/main/ribbon/ribbonmenu.js, client/main/store.js, client/main/store/pagemodules.js, client/main/store/pages.css, server/jamovi/server/instance.py, server/jamovi/server/jamovi.proto, server/jamovi/server/modules.py
- Added hide/showing of analyses in toolbar
- can run any analysis from the modules menu.
=> Upgrade to modules menu

client/analysisui/actions.js, client/analysisui/customcontrol.js, client/analysisui/defaultcontrols.js, client/analysisui/layoutaction.js, client/analysisui/layoutactionmanager.js, client/analysisui/main.js, client/analysisui/optionsview.js, client/main/optionspanel.js
For something that took so long there is very little to show for it in code here! 152 lines!
=> Upgrade to events system

client/main/editors/missingvalueeditor.js, client/main/vareditor/datavarwidget.js, client/main/vareditor/measurelist.css, client/main/vareditor/measurelist.js, client/main/vareditor/measurelistitem.js, client/main/vareditor/variablelist.js, client/main/vareditor/variablemodel.js, server/jamovi/server/formatio/omv.py
=> Various list box improvements

client/main/backstage.js, client/main/editors/transformeditor.js, client/main/infobox.js, client/main/main.js, client/main/ribbon/appmenu.js, client/main/ribbon/ribbonmenu.js, client/main/store.js, client/main/vareditor/computedvarwidget.js, client/main/vareditor/datavarlevelwidget.js, client/main/vareditor/editorwidget.js, client/main/vareditor/filterwidget.js
- Added keyed pause feature to keyboard
- Fixed focus issue with textboxes
- Gave the library keyboard focus when open
=> Fixed some keyboard issues

client/main/main.js, electron/app/main.js
Fixed the issue of opening files using a double click when the file name has special characters in it.
closes #768
closes #713
=> Fixed issue with opening files with mouse clicks with special chars

client/main/backstage.css, client/main/backstage.js
- also added keyboard support to file dialogues
=> Added search box to open dialog

.jshintrc, .travis.yml, client/main/backstage.js, client/main/instance.js, server/jamovi/server/clientconnection.py, server/jamovi/server/formatio/__init__.py, server/jamovi/server/instance.py, server/jamovi/server/instancemodel.py, server/jamovi/server/integrations/__init__.py, server/jamovi/server/integrations/base.py, server/jamovi/server/integrations/qp.py, server/jamovi/server/jamovi.proto, server/jamovi/server/utils/__init__.py
> saveFormat is typically either empty, or 'jamovi'. empty means the user hasn't saved it as a .omv file yet, and they need to be prompted where to save. saveFormat can have other values when the data set is loaded from an url, and it needs to be saved back to that url in a particular format.
it follows that when saveFormat isn't empty, the saveAs shouldn't appear either on save, or on save failure
=> Added QP Support

client/common/utils/formatio.js, client/main/backstage.js, client/main/instance.js, client/main/resultspanel.js, server/jamovi/server/analyses.py, server/jamovi/server/instance.py, server/jamovi/server/utils/__init__.py, server/jamovi/server/utils/apa7_cls.py, server/jamovi/server/utils/latexify.py
This work contributed under the terms of the jamovi CLA.
=> Latex export

server/jamovi/server/utils/latexify.py
made converting colspan to single table cells generic (earlier, it could only handle colspan="2")
=> Bug-fix: LaTeX bundle export error #878

server/jamovi/server/utils/latexify.py
The third change (l. 331) fixes another issue when commenting out figure because they could not be created / downloaded
=> Fix two travis issues

client/main/instance.js, client/main/resultspanel.js, client/resultsview/array.js, client/resultsview/group.js
- fix to export issue
- fix for situation when results item changes type
=> Fix to results panel

client/main/instance.js, client/main/resultspanel.js, client/resultsview/element.js, client/resultsview/group.js, client/resultsview/main.js
- and issues with note menu items
- and issue with removing note
=> fix to double pb decoding issue

client/analysisui/variableslistbox.js
- Add button covered controls below stopping them from working.
=> Fixed issue with output control

client/analysisui/layoutcell.js, client/analysisui/layoutcollapseview.css, client/analysisui/layoutcollapseview.js, client/analysisui/layoutsupplierview.css, client/analysisui/main.less, client/common/toolbar/toolbar.js, client/main/backstage.css, client/main/backstage.js, client/main/contextmenu.css, client/main/contextmenu/contextmenubutton.css, client/main/editors/operatordropdown.css, client/main/editors/transformeditor.css, client/main/jamovi.css, client/main/ribbon/ribbonmenu.css, client/main/ribbon/ribbonmenu.js, client/main/tableview.css, client/main/vareditor/dropdown.css, client/main/vareditor/filterwidget.css, client/main/vareditor/recodedvarwidget.css, client/resultsview/annotation.css
- also fixed issue with the model toolbar
=> Added visibility to opacity transitions

client/main/selection.js, client/main/variablesview.js
- fixed context menu issue
- fixed selection issue
=> fixes to variables page

client/main/ribbon/appmenu.js
* Color theme changes to "Greys" on change to bw theme
=> Add black and white plot theme

server/jamovi/server/instance.py
=> Fix to analysis updating on row insertion/deletion

client/main/dataset.js, client/main/main.js, client/main/tableview.css, client/main/tableview.js, client/main/viewcontroller.js
=> Fixed issues so that direct ime data input is supported

client/common/i18n.js, client/main/main.js, client/main/ribbon/appmenu.css, client/main/ribbon/appmenu.js, client/main/settings.js, server/jamovi/server/backend.py, server/jamovi/server/formatio/exceptions.py, server/jamovi/server/server.py, server/jamovi/server/session.py, server/jamovi/server/settings.py
this is a start ... i've left a few critical things for you, but i figured this would get you started.
=> Added setting for language selection

client/analysisui/layoutsupplierview.js
Maybe I picked the wrong base on my branch, you can merge it manually... thanks @jonathon-love
=> Added untranslated strings

client/main/backstage.js, client/main/jamovi.css, client/main/ribbon.css, client/main/ribbon/ribbonmenu.css, client/main/tableview.css, client/main/tableview.js
- Bring notification to front
- Fixed tab in safari
- Fixed Export browsing dialog
- fixed scrolling issue in modules menu
- improved touch support
=> Various Bug fixes

client/common/selectionloop.js, client/main/contextmenu.js, client/resultsview/annotation.js, client/resultsview/heading.js
fixed issue with right click menu in results
=> Fix to right click menu issue

server/jamovi/server/utils/latexify.py
Could you have a look at line 229 (and the line I commented out underneath). Why did you use group here? If I am using it for transforming HTML-files that I directly export from jamovi into LaTeX (those contain B64-encoded PNGs), the original line (i.e., 230) throws an error. Is B64-export any different in the server-version? If so, feel free to revert it.
Instead of your solution, I remove the padding in the beginning which makes the resulting HTML a little easier to read and, in case, to debug.
=> Fixed errors in LaTeX-export

client/main/backstage.css, client/main/backstage.js
- changed some flexboxes to grids
- toggle z-index to force render
=> Fix for backstage not rendering properly using chrome

client/analysisui/gridcombobox.js
=> Fix for listbox not updating when toggling between analyses

client/main/vareditor/formulatoolbar.js, server/jamovi/server/compute/functions.py
Added VMAD functions to get the Median Absolute Deviation and VMADR for Robusta.
=> Add: Median Absolute Deviation

client/main/utils/clipboardprompt.js
- Using ctrl-c on the copy prompt didn't working in all browsers. It does now.
=> Fixed minor issue with copying on web

client/analysisui/layoutactionmanager.js
- Now only the effected option is effected not all options.
=> Fixed issue when a u.yaml condition string is corrupt

client/analysisui/actions.js
This change will effect
- ANCOVA
- ANOVA
- RM ANOVA
- Linear Regression
- Log-Linear Regression
- Binomial Logistic Regression
- Ordinal Logistic Regression
=> Fix for certain analyses freezing

README.md, poetry.lock, pyproject.toml
=> Add ruff as autoformatter

client/analysisui.html, client/common/focusloop.js, client/main/main.js, client/main/optionspanel.js, client/main/resultspanel.js, client/main/tableview.js
- Allows for easier navigation to the options panel and results panel for a11y
=> Added alt arrow shortcuts for analysis options and results.

client/main/main.ts
=> Fixed issue with close dialog in non English translations

electron/app/preload.js
This small PR fixes a bug caused by attempting to modify clipboard data destructured as constants.
=> Resolve issue in paste from clipboard logic
